name: votenamadmin
description: Namibia Voting System - Admin Panel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.18.1
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  cached_network_image: ^3.3.0
  file_picker: ^5.5.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logovotenam.png

